#include <string.h>

#include "esp_log.h"
#include "esp_http_server.h"

#include "http_server.h"

static const char *TAG = "http_server";

/* Symbols generated by the linker for every file listed in EMBED_FILES.
   These are addresses in flash, not RAM buffers. The asm() label maps the
   mangled linker symbol onto a readable C identifier. */
extern const uint8_t index_html_start[] asm("_binary_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_index_html_end");
extern const uint8_t style_css_start[]  asm("_binary_style_css_start");
extern const uint8_t style_css_end[]    asm("_binary_style_css_end");
extern const uint8_t app_js_start[]     asm("_binary_app_js_start");
extern const uint8_t app_js_end[]       asm("_binary_app_js_end");

typedef struct {
    const char    *uri;
    const char    *content_type;
    const uint8_t *start;
    const uint8_t *end;
} static_asset_t;

/* Adding a new file means adding one row here plus one line in CMakeLists. */
static const static_asset_t s_assets[] = {
    { "/",           "text/html",              index_html_start, index_html_end },
    { "/index.html", "text/html",              index_html_start, index_html_end },
    { "/style.css",  "text/css",               style_css_start,  style_css_end  },
    { "/app.js",     "application/javascript", app_js_start,     app_js_end     },
};

#define ASSET_COUNT (sizeof(s_assets) / sizeof(s_assets[0]))

/* Catch-all handler for every GET request. */
static esp_err_t static_get_handler(httpd_req_t *req)
{
    for (size_t i = 0; i < ASSET_COUNT; i++) {
        if (strcmp(req->uri, s_assets[i].uri) != 0) {
            continue;
        }

        const size_t len = s_assets[i].end - s_assets[i].start;

        ESP_LOGI(TAG, "GET %s -> %u bytes, type %s, fd %d",
                 req->uri, (unsigned) len, s_assets[i].content_type,
                 httpd_req_to_sockfd(req));

        httpd_resp_set_type(req, s_assets[i].content_type);
        /* Development only: stop the browser from reusing a stale copy
           after the firmware is reflashed. */
        httpd_resp_set_hdr(req, "Cache-Control", "no-store");

        return httpd_resp_send(req, (const char *) s_assets[i].start, len);
    }

    ESP_LOGW(TAG, "No asset registered for %s", req->uri);
    httpd_resp_send_err(req, HTTPD_404_NOT_FOUND, "Asset not found");
    return ESP_FAIL;
}

static const httpd_uri_t static_uri = {
    .uri      = "/*",
    .method   = HTTP_GET,
    .handler  = static_get_handler,
    .user_ctx = NULL,
};

httpd_handle_t http_server_start(void)
{
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    config.lru_purge_enable = true;
    config.uri_match_fn     = httpd_uri_match_wildcard;

    httpd_handle_t server = NULL;

    ESP_LOGI(TAG, "Starting HTTP server on port %d", config.server_port);

    esp_err_t err = httpd_start(&server, &config);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "httpd_start failed: %s", esp_err_to_name(err));
        return NULL;
    }

    // Registration order matters: httpd returns the first matching handler,
    // so the "/*" catch-all must always be registered last.
    ESP_ERROR_CHECK(httpd_register_uri_handler(server, &static_uri));

    ESP_LOGI(TAG, "Server started, %u asset(s) available", (unsigned) ASSET_COUNT);
    return server;
}

void http_server_stop(httpd_handle_t server)
{
    if (server != NULL) {
        httpd_stop(server);
    }
}
